# Generated by Django 6.0.5 on 2026-07-08 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0008_intermediatetable_order_intermediatetable_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediatetable',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='my_shop.order'),
        ),
    ]
